name: 'Deploy Website'
 
# Trigger configuration automatically when new code pushed to main
on:
  push:
    branches: ['main']
 
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
 
jobs:
  # Build Job -- compile TS
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v5
      - name: 'Setup Node'
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
      - name: 'Build Website'
        run: npm ci && npm run build
      - name: 'Upload artifact'
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist
  # Deploy Job
  deploy:
    name: 'Deploy'
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 'Deploy to GitHub Pages'
        id: deployment
        uses: actions/deploy-pages@v4